---
version: '3.4'

services:

    aiidalab:
        image: ${REGISTRY:-}${QE_IMAGE:-aiidalab/qe}${TAG}
        environment:
            TZ: Europe/Zurich
            DOCKER_STACKS_JUPYTER_CMD: notebook
            SETUP_DEFAULT_AIIDA_PROFILE: 'true'
            AIIDALAB_DEFAULT_APPS: ''
            JUPYTER_TOKEN: ${JUPYTER_TOKEN}
        ports:
            - 0.0.0.0:${AIIDALAB_PORT:-8998}:8888
