---
name: Build environment
description: Create build environment

inputs:
    architecture:
        description: architecture to be run on
        required: true
        type: string

runs:
    using: composite
    steps:
        # actions/setup-python doesn't support Linux arm64 runners
        # See: https://github.com/actions/setup-python/issues/108
        # python3 is manually preinstalled in the arm64 VM self-hosted runner
        - name: Set Up Python 🐍
          if: ${{ inputs.architecture == 'amd64' }}
          uses: actions/setup-python@v4
          with:
              python-version: 3.x

        - name: Install Dev Dependencies 📦
          if: ${{ inputs.architecture == 'amd64' }}
          run: |
              pip install --upgrade pip
              pip install --upgrade -r docker/requirements-dev.txt
          shell: bash

        - name: Install Dev Dependencies 📦
          if: ${{ inputs.architecture == 'arm64' }}
          run: |
              pip install --upgrade pip
              pip install --upgrade -r docker/requirements-dev-arm64.txt
          shell: bash
