---
name: Downstream tests
description: Integration downstream tests of the freshly built image

inputs:
    architecture:
        description: Image architecture
        required: true
        type: string
    runsOn:
        description: GitHub Actions Runner image
        required: true
        type: string

runs:
    using: composite

    steps:
        - name: Set jupyter token env
          run: echo "JUPYTER_TOKEN=$(openssl rand -hex 32)" >> $GITHUB_ENV
          shell: bash

        - name: Run pytest to test image is working
          run: TAG=newly-baked pytest tests_integration/test_image.py
          shell: bash

        - name: Run pytest for Chrome
          if : ${{ inputs.architecture == 'amd64' }}
          run: TAG=newly-baked pytest --driver Chrome tests_integration/test_app.py
          shell: bash

        - name: Upload screenshots as artifacts
          if : ${{ inputs.architecture == 'amd64' }}
          uses: actions/upload-artifact@v4
          with:
              name: Screenshots-CI-${{ inputs.architecture }}
              path: screenshots/
              if-no-files-found: error
