---
name: Downstream tests
description: Integration downstream tests the bulid image

inputs:
    architecture:
        description: Image architecture
        required: true
        type: string
    runsOn:
        description: GitHub Actions Runner image
        required: true
        type: string

runs:
    using: composite

    steps:
        - name: Set jupyter token env
          run: echo "JUPYTER_TOKEN=$(openssl rand -hex 32)" >> $GITHUB_ENV
          shell: bash

        # The Firefox and its engine geckodrive need do be installed manually to run
        # selenium tests.
        - name: Install Firefox
          if : ${{ inputs.architecture == 'amd64' }}
          uses: browser-actions/setup-firefox@latest
          with:
              firefox-version: '96.0'

        - name: Install geckodriver
          if : ${{ inputs.architecture == 'amd64' }}
          run: |
              wget -c https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
              tar xf geckodriver-v0.30.0-linux64.tar.gz -C /usr/local/bin
          shell: bash

        - name: Run pytest for firefox
          if : ${{ inputs.architecture == 'amd64' }}
          run: VERSION=newly-baked pytest --driver Firefox tests_integration
          shell: bash

        - name: Run pytest for Chrome
          run: VERSION=newly-baked pytest --driver Chrome tests_integration
          shell: bash

        - name: Upload screenshots as artifacts
          if: always()
          uses: actions/upload-artifact@v3
          with:
              name: Screenshots-CI-${{ inputs.architecture }}
              path: screenshots/
              if-no-files-found: error
