---
name: Release

on:
    push:
        tags:
            - v*
        branches:
            - release/*

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'

            - name: Install pypa/build
              run: python -m pip install build

            - name: Build a  binary wheel for the aiidalab_qe_workchain module
              run: >-
                  python -m
                  build
                  --sdist
                  --wheel
                  --outdir dist/
                  src/

            - name: Upload distribution artifact
              uses: actions/upload-artifact@v2
              with:
                  name: release
                  path: dist/

    publish:

        needs: [build]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/download-artifact@v2
              name: Download distribution artifact
              with:
                  name: release
                  path: dist/

            - uses: softprops/action-gh-release@v0.1.14
              name: Create release
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  files: |
                      dist/*
                  generate_release_notes: true
