---
name: Release

on:
    pull_request:
        branches:
            - release/**
    release:

jobs:

    test-build:

        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v4

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Install pypa/build
              run: python -m pip install build

            - name: Build a  binary wheel for the aiidalab_qe module
              run: >-
                  python -m
                  build
                  --sdist
                  --wheel
                  --outdir dist/

            - name: Upload distribution artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release
                  path: dist/
