name: release

on:
  push:
    branches:
      - master

jobs:

  publish-metadata:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Check out app
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r metadata/requirements.txt

      - name: Compile metadata
        run: |
          python metadata/compile.py

      - name: Publish metadata
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: metadata/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
