---
name: Release

on:
    push:
        tags:
            - v*
        branches:
            - release/*

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'

            - name: Install pypa/build
              run: python -m pip install build

            - name: Build a binary wheel and a source tarball
              run: >-
                  python -m
                  build
                  --sdist
                  --wheel
                  --outdir dist/

            - name: Upload distribution artifact
              uses: actions/upload-artifact@v2
              with:
                  name: release
                  path: dist/

    publish:

        needs: [build]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/download-artifact@v2
              name: Download distribution artifact
              with:
                  name: release
                  path: dist/

            - name: Publish distribution on Test PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              if: startsWith(github.ref, 'refs/heads/release/')
              with:
                  user: __token__
                  password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                  repository_url: https://test.pypi.org/legacy/
                  skip_existing: true

            - uses: softprops/action-gh-release@v0.1.14
              name: Create release
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  files: |
                      dist/*
                  generate_release_notes: true

            - name: Publish distribution on PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
